# Generated by Django 5.2 on 2025-04-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_made', models.PositiveIntegerField(default=0)),
                ('fg_attempted', models.PositiveIntegerField(default=0)),
                ('three_pt_made', models.PositiveIntegerField(default=0)),
                ('three_pt_attempted', models.PositiveIntegerField(default=0)),
                ('ft_made', models.PositiveIntegerField(default=0)),
                ('ft_attempted', models.PositiveIntegerField(default=0)),
                ('oreb', models.PositiveIntegerField(default=0)),
                ('dreb', models.PositiveIntegerField(default=0)),
                ('ast', models.PositiveIntegerField(default=0)),
                ('stl', models.PositiveIntegerField(default=0)),
                ('blk', models.PositiveIntegerField(default=0)),
                ('to', models.PositiveIntegerField(default=0)),
                ('pf', models.PositiveIntegerField(default=0)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='stats.opponentteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='stats.player')),
            ],
        ),
    ]
